name: Docker Compose CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Containers
        run: docker compose build

      - name: Start Containers
        run: docker compose up -d
